CREATE DATABASE IF NOT EXISTS HANKAN;
CREATE DATABASE IF NOT EXISTS TESTDB;

-- CREATE USER IF NOT EXISTS 'hankan'@'%' IDENTIFIED BY 'hankan';
--
-- GRANT ALL PRIVILEGES ON HANKAN.* TO 'hankan'@'%';
GRANT ALL PRIVILEGES ON TESTDB.* TO 'hankan'@'%';

FLUSH PRIVILEGES;