// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW1Ag98TRJR11huU71arjNO6sNKlZRKDg',
    appId: '1:608255451330:web:0fe6867ea635b76caddb5b',
    messagingSenderId: '608255451330',
    projectId: 'hankan-9423',
    authDomain: 'hankan-9423.firebaseapp.com',
    storageBucket: 'hankan-9423.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBocKeMNMTyAUi7UCjI3WUKj_RHBf-hzaw',
    appId: '1:608255451330:android:7afa4557f5f6897faddb5b',
    messagingSenderId: '608255451330',
    projectId: 'hankan-9423',
    storageBucket: 'hankan-9423.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqJbxzfVyDCJrtL9r1GE_bGU2dQVV42mc',
    appId: '1:608255451330:ios:195d88a75a7cf344addb5b',
    messagingSenderId: '608255451330',
    projectId: 'hankan-9423',
    storageBucket: 'hankan-9423.firebasestorage.app',
    iosBundleId: 'com.example.hankan',
  );
}
